// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// feetech_bus_tx //
// -------------- //

#define feetech_bus_tx_wrap_target 0
#define feetech_bus_tx_wrap 6
#define feetech_bus_tx_pio_version 0

static const uint16_t feetech_bus_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe081, //  1: set    pindirs, 1
    0xa0ef, //  2: mov    osr, ~osr
    0xe527, //  3: set    x, 7                   [5]
    0x6681, //  4: out    pindirs, 1             [6]
    0x0044, //  5: jmp    x--, 4
    0xe680, //  6: set    pindirs, 0             [6]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program feetech_bus_tx_program = {
    .instructions = feetech_bus_tx_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = feetech_bus_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config feetech_bus_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + feetech_bus_tx_wrap_target, offset + feetech_bus_tx_wrap);
    return c;
}
#endif

// -------------- //
// feetech_bus_rx //
// -------------- //

#define feetech_bus_rx_wrap_target 0
#define feetech_bus_rx_wrap 3
#define feetech_bus_rx_pio_version 0

static const uint16_t feetech_bus_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program feetech_bus_rx_program = {
    .instructions = feetech_bus_rx_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = feetech_bus_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config feetech_bus_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + feetech_bus_rx_wrap_target, offset + feetech_bus_rx_wrap);
    return c;
}
#endif

